### ISSUE TITLE
problem in footprints visualization

### ISSUE THREAD

**Issue by maxpittore** [GFZ-Centre-for-Early-Warning/REM_RRVS#1]
when a building is modified but not completed, once updated it apparently disappears from the map.
In reality the color for updated buildings is very similar to background. 
(mozilla 44.0 - ubuntu 12.04)

**Comment by m-haas** [comment]
Switched to more saturated colors for status visualization in 
commit [3688948](https://github.com/GFZ-Centre-for-Early-Warning/REM_RRVS/commit/3688948a42e6bd4f93b04674044e011b7f612d0b)
